name: First interaction

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: self-hosted
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          repo-token: ${{ secrets.SECRET_TOKEN }}
            
